# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-28 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171128_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
